### ISSUE TITLE
Clean up passing of pt_regs to signal syscalls

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#132]
Some of the signal syscalls, at least `debug_setcontext()`, `swapcontext()`, `sigreturn()` and `rt_sigreturn()` are getting `pt_regs` by declaring that they take 7 arguments and getting `pt_regs` as the 7th argument in `r9`.

Possibly at some point that was necessary, but these days we can just use `current_pt_regs()`.

We should clean that up:
- use `current_pt_regs()` in the relevant syscalls
- fix their signatures to only take the relevant arguments
- stop passing `pt_regs` in r9 (perhaps NULL it out to be safe?)
- convert the signal syscalls to use `SYSCALL_DEFINE`

**Comment by chleroy** [comment]
Apparently, that was changed in v4.18 by commit https://github.com/linuxppc/linux/commit/f3675644e

**Comment by chleroy** [comment]
> 
> 
> Most of this was done by Viro in
> f3675644e172 `powerpc/syscalls: signal_{32, 64} - switch to SYSCALL_DEFINE`.
> 
> Except:
> 
>     * stop passing `pt_regs` in r9 (perhaps NULL it out to be safe?)

Since commit https://github.com/linuxppc/linux/commit/68b34588e2027f699a3c034235f21cd19356b2e6 syscalls are called by C code on PPC64.
Since commit https://github.com/linuxppc/linux/commit/6f76a01173ccaa363739f913394d4e138d92d718 syscalls are called by C code on PPC32

So nobody knows what goes in r9 now but nobody minds either.

**Comment by mpe** [comment]
Agreed, thanks for chasing up the loose ends @chleroy
