### ISSUE TITLE
Make strict kernel RWX the default on 64-bit

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#223]
We have most of the code to do strict Kernel RWX, written by Balbir. It tries to align the init text, init data, data etc. starting on a large page boundary (16M on hash 1M on Radix), so that we can still use large pages for the linear mapping.

Currently though the code does not work correctly for relocatable kernels, and so the strict RWX option depends on RELOCATABLE being disabled.

The first issue is that when running relocatable we have executable code at 0x0, the exception vectors, then we have some gap which should not be executable. We need to make sure the page containing the exception vectors is marked executable but not writable, and also that any remaining space in that page is not given back to the page allocator.

Similarly when the kernel is not at 0x0 we need to make sure only the kernel text is executable, and not surrounding areas, or that any surrounding areas are not given to the page allocator.

Then there is the problem that when running relocatable the kernel may be placed on a non-large-page boundary by the user. The code either needs to detect that and complain very loudly, or do the appropriate modifications to the mappings and init text/data that is freed to make sure everything is correct.

A correct implementation of strict kernel RWX must enforce the following for all pages of the linear mapping:
 - no pages are both writable and executable
 - all executable pages are reserved, ie. not available for kernel/user allocations
 - pages used for init text are not mapped executable after they're freed
 - all read-only data is mapped read only
 - areas marked nomap are not mapped (we don't support this currently)

Balbir sent some patches previously:
https://patchwork.ozlabs.org/patch/795744/
https://patchwork.ozlabs.org/patch/795743/
https://patchwork.ozlabs.org/patch/795745/

They enable strict RWX + Relocatable for Radix and hash.

But the hash handling (2nd patch) is a bit of a hack.

They'll also need reworking because the Radix code has had some fixes since then.

**Comment by chleroy** [comment]
I suppose you are talking about 64 bits here.

On 32 bits, at the time being, strict Kernel RWX implies to not use block mapping (Large Pages on the 4xx and 8xx, BATs on book3s/32). This means a severe performance reduction. 

And in addition, it doesn't work on book3s/32 hash, because pages PP bits only has RW for kernel pages (no PP bits for RO with no access to user) and no exec protection either. Only the 603 can protect pages against kernel write and against execution.

So, first step is to make strict kernel RWX work with large pages and BATs. This solves both problems because (except on the 601) BATs can be set X or NX and RW or RO.

A series for that is proposed here https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=85401

**Comment by mpe** [comment]
Yeah sorry I was meaning 64-bit. I'll try and review that series at some point, though I don't really know the 32-bit code that well so if it's working for you I'm inclined to merge it.

**Comment by mpe** [comment]
@ruscur is looking at this.

**Comment by chleroy** [comment]
Looks like strict kernel RWX has been completely disabled on 64-bit, see https://github.com/linuxppc/linux/commit/8659a0e0efdd975c73355dbc033f79ba3b31e82c

**Comment by chleroy** [comment]
Strict kernel RWX is back on 64 bits.
In the meantime it has been improved on 32 bits, it now uses block mappings.

So it could be made ARCH_OPTIONAL_KERNEL_RWX_DEFAULT

**Comment by ruscur** [comment]
We could do it now.  Since the last time we tried, we've found and fixed a bug in radix, a bug in hash and the bug affecting kprobes.

I am concerned of a repeat event where we switch it on by default and people start hitting bugs that we don't hit.  But that's what release candidates are for, right?

**Comment by daxtens** [comment]
Strict Module RWX is upstream as of 5.14-rc1: e.g. c35717c71e983ed55d61e523cbd11a798429bc82 . I don't think it or Strict Kernel RWX is on by default yet though.

**Comment by ruscur** [comment]
Closing this now, thanks Christophe.
