### ISSUE TITLE
Feature: 2nd DAWR support on baremetal and powervm

### ISSUE THREAD

**Issue by BangoriaRavi** [linuxppc/issues#313]
Please consider:

powerpc/watchpoint: Enable 2nd DAWR on baremetal and powervm: (v3)
https://lore.kernel.org/lkml/20200708045046.135702-1-ravi.bangoria@linux.ibm.com

Introduce PPC_DEBUG_FEATURE_DATA_BP_DAWR_ARCH_31 (v1)
https://lore.kernel.org/lkml/20200709122944.173744-1-ravi.bangoria@linux.ibm.com

**Comment by BangoriaRavi** [comment]
powerpc/watchpoint: Enable 2nd DAWR on baremetal and powervm: (v5)
https://lore.kernel.org/linuxppc-dev/20200723090813.303838-1-ravi.bangoria@linux.ibm.com

Introduce PPC_DEBUG_FEATURE_DATA_BP_DAWR_ARCH_31 (v2)
https://lore.kernel.org/linuxppc-dev/20200723093330.306341-1-ravi.bangoria@linux.ibm.com

**Comment by mpe** [comment]
I've applied the main series to next.

I'd like some acknowledgment from someone on the toolchain side before I merge the `PPC_DEBUG_FEATURE_DATA_BP_DAWR_ARCH_31` patch.

**Comment by racardoso** [comment]
We are now discussing a concern from Pedro related to ` CONFIG_PERF_EVENTS` he is afraid that DAWR does not generate the interrupt when hit the watchpoint if `CONFIG_PERF_EVENTS=OFF` because the kernel doesn't set the necessary privileges on the old interface. Right now there is a discussion about that. We are waiting for a agreement on this before we can get the acknowledgement here. I don't think this will be a long discussion.

**Comment by BangoriaRavi** [comment]
Introduce PPC_DEBUG_FEATURE_DATA_BP_ARCH_31 (v3):
https://lore.kernel.org/linuxppc-dev/20200805062750.290289-1-ravi.bangoria@linux.ibm.com

It also contains fix for issue mentioned in above comment.

**Comment by BangoriaRavi** [comment]
Introduce PPC_DEBUG_FEATURE_DATA_BP_ARCH_31 (v4):
https://lore.kernel.org/linuxppc-dev/20200817102330.777537-1-ravi.bangoria@linux.ibm.com/

With more fixes.

**Comment by mpe** [comment]
That series has gotten quite big for post rc1.

The problems with `CONFIG_HAVE_HW_BREAKPOINT=n` are long standing AIUI, so can we untangle those from the `PPC_DEBUG_FEATURE_DATA_BP_ARCH_31` addition? Or do we want that flag to indicate that all those bugs are fixed?

**Comment by BangoriaRavi** [comment]
I understand. Sorry for the delay.

Bug fixes are needed for gdb to make correct decision based on `PPC_DEBUG_FEATURE_DATA_BP_ARCH_31`. Pedro, Rogerio, might be able to provide more detail.

**Comment by rnav** [comment]
My understanding is that those fixes must go in before the debug feature addition. I think we are ok if the fixes go in this cycle, while the debug feature addition is delayed to the next release. 

It still would be good to get Pedro/ @racardoso 's ack for the fixes.

**Comment by pedromfcarvalho** [comment]
I ran some tests and found additional potential issues with some of the ptrace behavior, I'll discuss these with Ravi in more detail.

The feature bit patch itself ([5/6]) from the series is what we want, and looks good to us. I wasn't able to test the new feature, so that's from inspecting the patch. However, it might be necessary to resolve these other issues too, and I didn't inspect in detail the other patches of the series.

I did test setting a watchpoint without perf events enabled, and it triggers, so this part works, and system calls that affect the watched region work too.

I'll give some additional details as to why the fixes are needed.

Some time ago (around 2012), it was decided between GDB and the kernel that GDB would rely on the feature bits being non zero to indicate a functional PPC_PTRACE_SETHWDEBUG interace. I'm not sure I understand why, and if the interface was actually non-functional back then.

In addition, the kernel only set the feature bits to non-zero when perf events were enabled, and therefore CONFIG_HW_BREAKPOINT too. Some time later a bug was introduced that caused watchpoints set with PPC_PTRACE_SETHWDEBUG not to trigger when perf events were disabled. At this point the interface did indeed become non-functional, and in this case the feature bits were zero, which was possibly a coincidence.

Because features were zero when perf events were disabled, GDB would fall back to using the old interface (PTRACE_SET_DEBUGREG), which would work.

By setting the feature bit when perf events are disabled without first fixing the bug, GDB would no longer fall back to the old interface, it would use the new interface which would not work. Again, this only happens when perf events are disabled.

I would not mind if the bit were set only for the case when perf events are enabled, which would not require the fixes, and adding the bit for the case when perf events are disabled later on. We do think it makes sense for the bit to be set when perf events are disabled too at some point, however. However, as Ravi mentioned, this would probably be a strange change in the ABI: when perf events are disabled it would go from not showing the new feature bit to showing it in the future.

**Comment by BangoriaRavi** [comment]
Introduce PPC_DEBUG_FEATURE_DATA_BP_ARCH_31 (v5):
https://lore.kernel.org/linuxppc-dev/20200825043617.1073634-1-ravi.bangoria@linux.ibm.com

> I ran some tests and found additional potential issues with some of the ptrace behavior, I'll discuss these with Ravi in more detail.

v5 covers fixes for this.

**Comment by BangoriaRavi** [comment]
Introduce PPC_DEBUG_FEATURE_DATA_BP_ARCH_31 (v6):
https://lore.kernel.org/linuxppc-dev/20200902042945.129369-1-ravi.bangoria@linux.ibm.com

**Comment by mpe** [comment]
Applied to next.
