### ISSUE TITLE
Can stolen time calculation be done separately from CONFIG_VIRT_CPU_ACCOUNTING_NATIVE

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#405]
Most distros[1] have now switched to `VIRT_CPU_ACCOUNTING_GEN`, because it's selected by `NO_HZ_FULL`.

That means `CONFIG_VIRT_CPU_ACCOUNTING_NATIVE` can't be selected, which has the effect of disabling our stolen time calculation code. No one has reported that as a problem, so maybe it isn't. But it's possible we could still do the stolen time calcuation separate from `CONFIG_VIRT_CPU_ACCOUNTING_NATIVE`, the link between the two seems to be only historical.

1: At least RHEL, SLES, Ubuntu & Void.

**Comment by mpe** [comment]
Nick posted a series to do this:

https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=300889&state=7

It had some minor build errors, needs a v2.

**Comment by npiggin** [comment]
Series is in powerpc next

**Comment by npiggin** [comment]
Fixed with commit 0e8a6313280 ("powerpc/pseries: Implement CONFIG_PARAVIRT_TIME_ACCOUNTING").  VIRT_CPU_ACCOUNTING_NATIVE has a couple of features that GEN accounting does not (separate user and sys stolen time, and scaled CPU time accounting). But we at least have basic stolen time equivalent to what x86 provides now.
