### ISSUE TITLE
Per-task speculation control

### ISSUE THREAD

**Issue by ruscur** [linuxppc/issues#422]
Most of our mitigations are switchable at runtime through debugfs, but there's [prctl()s for them too](https://www.kernel.org/doc/Documentation/userspace-api/spec_ctrl.rst) that we could wire up to enable per-process control.

I haven't taken much of a look at how complex it would be, but it'd be nice to have.  See https://github.com/KSPP/linux/issues/48

**Comment by mpe** [comment]
I'm not sure we can actually implement any of them with the controls we have.

There's `PR_SPEC_STORE_BYPASS`, but our speculative store bypass mitigation is applied on kernel entry/exit. So we can't disable that on a per-task basis, because that would expose the kernel.

There's `PR_SPEC_L1D_FLUSH`, similar story. We do the L1 flush on kernel entry/exit, and can't disable it without exposing the kernel. We could do an additional flush when context switching, but I don't think that achieves anything when we're already doing it on kernel entry/exit. Additionally AFAIK we have no way to flash invalidate the L1 on Power10.

The last one is `PR_SPEC_INDIRECT_BRANCH`. The performance killing mitigation there is the P9 indirect branch cache disable, but that's not controllable by the kernel at runtime. On P9 DD2.3 and P10 we only do the count cache/link stack flush on context switch. We *could* disable that if we are switching between two processes that have *both* disabled the prctl, but that seems incredibly unlikely in practice.

**Comment by ruscur** [comment]
Thanks for having a look.  If we can't have per-task control of the mitigations we currently have, I believe we can still do it for the DEXCR bits in P10 ([ISA 3.1b](https://files.openpower.foundation/s/dAYSdGzTfW4j2r2), which are:

- Speculative Branch Hint Enable
- Indirect Branch Recurrent Target Prediction Disable
- Subroutine Return Address Prediction Disable

but it probably makes more sense to track that in a separate DEXCR support issue.
