### ISSUE TITLE
Enable 9P fs in pseries defconfig

### ISSUE THREAD

**Issue by npiggin** [linuxppc/issues#439]
QEMU has a virtfs driver that allows guest to mount subdirectories on host with 9P_FS. Could we enable this in pseries defconfig? Something like -

+CONFIG_NET_9P=m
+CONFIG_NET_9P_FD=m
+CONFIG_NET_9P_VIRTIO=m
+# CONFIG_NET_9P_RDMA is not set
+# CONFIG_NET_9P_DEBUG is not set
+CONFIG_NETFS_SUPPORT=m
+# CONFIG_NETFS_STATS is not set
+CONFIG_9P_FS=m
+CONFIG_9P_FS_POSIX_ACL=y
+# CONFIG_9P_FS_SECURITY is not set
`

**Comment by mpe** [comment]
I'd like to eventually merge/replace `pseries_(le)_defconfig` with `ppc64le_guest_defconfig`.

The latter is generated by merging `arch/powerpc/configs/guest.config` into the result of defconfig, so it works for LE and BE.

Personally when I enable 9P I build it in, so that it's usable without requiring modules. That would be my preference, though I guess we'd want to confirm it doesn't bloat the image too much.

**Comment by npiggin** [comment]
Merged upstream.
